# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proof < Formula
  desc "Deterministic proof records and offline verification CLI"
  homepage "https://github.com/Clyra-AI/proof"
  version "0.4.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.4.6/proof_0.4.6_darwin_amd64.tar.gz"
      sha256 "293b80689064ed683bffeb97d06592088ec056db2f69468a78f60657c2c84d35"

      def install
        bin.install "proof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.4.6/proof_0.4.6_darwin_arm64.tar.gz"
      sha256 "6658b0910c48287379caa32467c77af909f399135e34108457b5f865e5e84408"

      def install
        bin.install "proof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.4.6/proof_0.4.6_linux_amd64.tar.gz"
      sha256 "a40bf5568c05cc30a4c85c877e4dd150bdba99d97cc4c4ffc177b0ead7831c35"
      def install
        bin.install "proof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.4.6/proof_0.4.6_linux_arm64.tar.gz"
      sha256 "746f5272e4227389fbb426a9c822241a524dc2ac3594bcc3159bc83663b701a3"
      def install
        bin.install "proof"
      end
    end
  end
end
