# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proof < Formula
  desc "Deterministic proof records and offline verification CLI"
  homepage "https://github.com/Clyra-AI/proof"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.5.0/proof_0.5.0_darwin_amd64.tar.gz"
      sha256 "8a81fe51d73819e83a8844c67bca608e02e9ba455b57aafd3c5be920f2b2f759"

      def install
        bin.install "proof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.5.0/proof_0.5.0_darwin_arm64.tar.gz"
      sha256 "9faae659e14e57ee8a4647c40e5045f22ce8dbfeee03be9d5fad424d162b1356"

      def install
        bin.install "proof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.5.0/proof_0.5.0_linux_amd64.tar.gz"
      sha256 "5cdbb9d9b481259434b6d0d5c1c8468c8a4a88f901de54157daf5a64889ad544"
      def install
        bin.install "proof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.5.0/proof_0.5.0_linux_arm64.tar.gz"
      sha256 "9c34c461db92956371a32479b884f33eeb766a2c7be503e466b3ff58e4dc5ed2"
      def install
        bin.install "proof"
      end
    end
  end
end
