# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proof < Formula
  desc "Deterministic proof records and offline verification CLI"
  homepage "https://github.com/Clyra-AI/proof"
  version "0.4.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.4.6/proof_0.4.6_darwin_amd64.tar.gz"
      sha256 "143fe2d0ad1e38c70001259ace1b1b8dad0f4371d2c302dca42c1d4ffd2ad8bc"

      def install
        bin.install "proof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.4.6/proof_0.4.6_darwin_arm64.tar.gz"
      sha256 "c44f219dcd3df7049e02b69a62f2f1f30d249fce35e8a0ca9674a1d34fcbe82b"

      def install
        bin.install "proof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.4.6/proof_0.4.6_linux_amd64.tar.gz"
      sha256 "5d279000072eb1c2e4df52c662a983ef26039bdc6d1eda0ea22af93bb7633ead"
      def install
        bin.install "proof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Clyra-AI/proof/releases/download/v0.4.6/proof_0.4.6_linux_arm64.tar.gz"
      sha256 "16e6015be75f92010d1a43dc139c9a3946475bdf893f837e610bac693c022eb6"
      def install
        bin.install "proof"
      end
    end
  end
end
