# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrkr < Formula
  desc "Deterministic AI tooling discovery, risk scoring, and proof artifacts"
  homepage "https://github.com/Clyra-AI/wrkr"
  version "1.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Clyra-AI/wrkr/releases/download/v1.6.0/wrkr_1.6.0_darwin_amd64.tar.gz"
      sha256 "3bdaaada0500545dd2da2c9b90f9d2afae7115ad4f53a3b3da9552b9325a6ee1"

      def install
        bin.install "wrkr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Clyra-AI/wrkr/releases/download/v1.6.0/wrkr_1.6.0_darwin_arm64.tar.gz"
      sha256 "1d2b34da3538e87d1fcf9ef06af7f0cfee2251a2141a6f66f3a0340140ee35eb"

      def install
        bin.install "wrkr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Clyra-AI/wrkr/releases/download/v1.6.0/wrkr_1.6.0_linux_amd64.tar.gz"
      sha256 "95f9c81cada10ee9635b84cc34b0fd2c7c9efe37f25f6ca82a4f37b4d03e5e36"
      def install
        bin.install "wrkr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Clyra-AI/wrkr/releases/download/v1.6.0/wrkr_1.6.0_linux_arm64.tar.gz"
      sha256 "a26ed3c7f363461561473625ac94ba361c9b4060fe67d90a0bc2b0405e20eb23"
      def install
        bin.install "wrkr"
      end
    end
  end

  test do
    output = shell_output("#{bin}/wrkr --json")
    assert_match "\"status\":\"ok\"", output
  end
end
